In [1]:
import pandas as pd
import numpy as np
df = pd.read_excel(r"C:\Users\user\Documents\data_sentimen.xlsx")
df #cetak isi dataset

opini sentimen
0                                 berita cepat terkini  positif
1                                    tarik berita baru  positif
2                             berita bagus sesuai jadi  positif
3                                       aplikasi henti  negatif
4    berita terkini mantap percaya maju cnn indones...  positif
..                                                 ...      ...
995               profesional serang bijak perintah sa  positif
996  berita ber ulang ulang muncul berita banyak ik...  positif
997  berita diskredit pemerintahbila berita sampai ...  positif
998                                  baik berita terus  positif
999                                     hoax makan bos  negatif

[1000 rows x 2 columns]

In [2]:
df['sentimen'].value_counts() #ngitung banyakny masing" sentimen

positif    762
negatif    238
Name: sentimen, dtype: int64

In [3]:
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer 
vectorizer = CountVectorizer(decode_error="replace")
transformer = TfidfTransformer()
TFIDF = transformer.fit_transform(vectorizer.fit_transform(df['opini']))

In [4]:
print(TFIDF)

  (0, 1484)	0.5903623790795823
  (0, 290)	0.7594053882560392
  (0, 198)	0.27345149049729056
  (1, 1449)	0.6759484664579086
  (1, 198)	0.2175213219192423
  (1, 160)	0.7041151505284536
  (2, 1364)	0.5782152136506673
  (2, 624)	0.7083004473470406
  (2, 198)	0.18464387976903174
  (2, 121)	0.3603946179602781
  (3, 549)	0.8997260588626472
  (3, 85)	0.43645505954621283
  (4, 1484)	0.25137372409473735
  (4, 1143)	0.3233514995334712
  (4, 894)	0.6646253665265013
  (4, 870)	0.48734443113142245
  (4, 588)	0.29048482286410526
  (4, 312)	0.2347023061123105
  (4, 198)	0.1164344510446769
  (5, 1484)	0.3776025783115248
  (5, 1143)	0.4857244342639419
  (5, 997)	0.49361812665369764
  (5, 569)	0.5111632810494958
  (5, 121)	0.34138147570873056
  (6, 1059)	0.9726260170437941
  :	:
  (995, 1274)	0.508194081052707
  (995, 1187)	0.45937583676241306
  (995, 1146)	0.32232569836784586
  (995, 218)	0.508194081052707
  (996, 1571)	0.7021488048361499
  (996, 972)	0.2978217058708814
  (996, 570)	0.4021412447331863
 

In [5]:
  #Save model TFIDF
import pickle
pickle.dump(vectorizer.vocabulary_,open("TFIDF_sentimen_kfold.pkl","wb"))

In [6]:
labels = [] #membuat kolom labels
for data in df['sentimen']:#untuk data di df row kategori
    labels.append(data)
kolom = labels.pop
print(labels)

['positif', 'positif', 'positif', 'negatif', 'positif', 'positif', 'positif', 'negatif', 'positif', 'positif', 'negatif', 'positif', 'positif', 'negatif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'negatif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'negatif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'negatif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'positif', 'negatif', 'positif', 'positif', 'positif', 'positif'

In [7]:
#kemudian kategori diberi label
label=[]
for i in range(len(labels)): 
    if labels[i]=='positif':
        nilai = 1
        label.append(nilai)
    
    if labels[i]=='negatif':
        nilai = -1
        label.append(nilai)

In [9]:
print(label)

[1, 1, 1, -1, 1, 1, 1, -1, 1, 1, -1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, 1, 1, -1, 1, 1,

In [10]:
from sklearn import svm #metode untuk klasifikasi aspek / kategori
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer #untuk menghitung vsm dan tfidf #vsm =vector space model
from sklearn import metrics #metode untuk pembentukan matriks 1x1 1x2 1x3
from sklearn.metrics import accuracy_score #metod untuk pembentukan skor akurasi 
from sklearn.model_selection import KFold #metode untuk perhitungan kfold
import numpy as np 
import re #regular expression
import itertools #fungsi pengulangan tak terbatas
import matplotlib.pyplot as plt #pembentukan diagram
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC #suport vector classifier
from sklearn.metrics import classification_report



In [12]:
akurasi=[]
def avg_akurasiSVM(): ##fungsi untuk rata rata akurasi one vs rest classifier
    total = 0
    for i in range(5): ##lakukan 10 kali
        total = total + akurasi[i]
    print("Rata-rata akurasi keseluruhan SVM adalah :", total / 5)

In [14]:
from sklearn.svm import SVC #suport vector classifier
kFoldCrossValidation = KFold(n_splits=5, random_state=42, shuffle = True)#fungsi K-Fold Cross Validation melakukan insialisasi 10 kali iterasi
for latih, uji in kFoldCrossValidation.split(TFIDF, label):
    
    print("-----------------------------")
    print("Jumlah data latih: ", len(latih)) #berapa jmlah data latih
    print("Jumlah data uji: ", len(uji)) #berapa jumlah data uji
    print("\nData Latih: \n", latih) #menampilkan data latih
    print("\nData Uji: \n", uji)#menampilkan data uji
    dataLatih1, dataUji1 = TFIDF[latih], TFIDF[uji]#proses inisialisasi dari masing2 data latih/uji dijadikan nilai tfidf lalu di copy ke variabel dataLatih/Uji1
    label = np.array(label)
    dataLatih2, dataUji2 = label[latih], label[uji]#
    
    SVM = SVC(kernel = 'linear', C = 1)
    model = SVM.fit(dataLatih1, dataLatih2)
    prediksi = model.predict(dataUji1)
    
    print("\nHasil Prediksi SVM  : \n", prediksi)
    
    print("\nConfusion Matrix: \n", metrics.confusion_matrix(dataUji2, prediksi))
   
    akurasi.append(accuracy_score(dataUji2, prediksi))
    
    print("\nAkurasi SVM : ", accuracy_score(dataUji2, prediksi))
    print()\
    
    label_target = ['positif','negatif']
    print(metrics.classification_report(dataUji2, prediksi, labels=[1,-1]))#proses pembentukan confusin matrix
    
avg_akurasiSVM() #hasil rata rata multiclass

-----------------------------
Jumlah data latih:  800
Jumlah data uji:  200

Data Latih: 
 [  0   1   2   3   4   5   6   7   8   9  11  12  13  14  15  16  17  18
  19  20  21  22  24  26  27  28  29  31  32  33  34  35  36  37  38  40
  41  42  43  45  46  47  48  49  50  51  52  53  56  57  58  61  62  64
  65  68  69  71  73  74  75  77  79  80  81  82  83  84  85  87  89  90
  91  92  93  94  95  97  98  99 100 102 103 104 105 106 108 109 111 112
 113 114 115 116 117 118 119 121 122 123 124 125 126 127 128 129 130 131
 132 133 134 135 138 140 141 142 143 144 145 146 147 148 149 150 151 152
 153 154 155 156 157 159 160 161 162 163 164 165 166 167 169 170 171 172
 173 175 176 177 178 179 180 181 182 183 185 186 187 188 189 190 191 192
 193 194 195 196 197 200 201 202 203 204 205 206 207 211 212 214 216 217
 219 220 222 223 224 225 226 227 228 229 230 231 232 233 234 236 238 239
 240 241 242 243 245 246 248 249 250 251 252 253 255 257 258 262 263 264
 266 267 268 269 270 271 272 273 


Confusion Matrix: 
 [[ 19  22]
 [  5 154]]

Akurasi SVM :  0.865

              precision    recall  f1-score   support

           1       0.88      0.97      0.92       159
          -1       0.79      0.46      0.58        41

    accuracy                           0.86       200
   macro avg       0.83      0.72      0.75       200
weighted avg       0.86      0.86      0.85       200

-----------------------------
Jumlah data latih:  800
Jumlah data uji:  200

Data Latih: 
 [  0   1   2   3   4   5   6   7   8   9  10  13  14  16  17  20  21  23
  25  26  27  28  29  30  31  32  33  34  35  36  37  39  40  41  44  45
  47  48  49  52  53  54  55  56  58  59  60  62  63  64  65  66  67  69
  70  71  72  73  76  77  78  79  80  81  82  84  85  86  87  88  90  91
  95  96  97  98  99 101 102 103 105 106 107 108 109 110 111 112 115 118
 119 120 121 122 123 125 127 128 129 130 131 132 133 134 135 136 137 138
 139 140 141 143 144 145 146 147 148 150 151 152 155 156 157 158 159 160
 161


Hasil Prediksi SVM  : 
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1 -1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1
  1 -1 -1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1 -1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1 -1  1  1  1  1 -1  1  1  1  1  1  1 -1  1  1  1
  1  1  1 -1  1  1  1 -1  1  1  1  1  1  1  1 -1 -1  1 -1  1  1  1  1  1
 -1  1  1 -1 -1  1  1 -1  1 -1 -1  1 -1 -1  1  1 -1  1  1 -1  1 -1  1  1
 -1 -1  1  1  1  1  1  1]

Confusion Matrix: 
 [[ 23  23]
 [  6 148]]

Akurasi SVM :  0.855

              precision    recall  f1-score   support

           1       0.87      0.96      0.91       154
          -1       0.79      0.50      0.61        46

    accuracy                           0.85       200
   macro avg       0.83      0.73      0.76       200
weighted avg       0.85   

In [26]:
#save
# save the model to disk
import pickle
filename = 'Sentimen.sav'
pickle.dump(SVM, open(filename, 'wb'))

# Model

In [15]:
import string
import Sastrawi
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

In [16]:
kalimat = "sayangnya aplikasinya jelek, gak update" 
lower_case = kalimat.lower()
print (lower_case)

sayangnya aplikasinya jelek, gak update


In [17]:
punctuation = lower_case.translate(str.maketrans('','',string.punctuation)).strip()
print(punctuation)

sayangnya aplikasinya jelek gak update


In [18]:
tokenize = word_tokenize(punctuation)
print(tokenize)

['sayangnya', 'aplikasinya', 'jelek', 'gak', 'update']


In [19]:
factory = StopWordRemoverFactory()
stopword = factory.create_stop_word_remover()
hasil_stopword = []
for i in tokenize:
    word = stopword.remove(i)
    if word !='':
        hasil_stopword.append(word)
print(hasil_stopword)

['sayangnya', 'aplikasinya', 'jelek', 'gak', 'update']


In [20]:
factory = StemmerFactory()
stemmer = factory.create_stemmer()  
hasil_stemming = [] 
for i in hasil_stopword:
    word = stemmer.stem(i)
    if word !='':
        hasil_stemming.append(word) 
print(hasil_stemming)

['sayang', 'aplikasi', 'jelek', 'gak', 'update']


In [21]:
teks_ulasan=[' '.join(reversed(hasil_stemming))]
print(teks_ulasan)

['update gak jelek aplikasi sayang']


In [23]:
#Load TFIDF model
import pickle
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer
transformer = TfidfTransformer()
loaded_vec = CountVectorizer(decode_error="replace",vocabulary=pickle.load(open("TFIDF_sentimen_kfold.pkl", "rb")))
tfidf = transformer.fit_transform(loaded_vec.fit_transform(teks_ulasan))

In [24]:
print (tfidf)

  (0, 1303)	0.5
  (0, 650)	0.5
  (0, 479)	0.5
  (0, 85)	0.5


In [27]:
loaded_SVM_model = pickle.load(open('Sentimen.sav', 'rb'))

In [28]:
print (loaded_SVM_model)

SVC(C=1, kernel='linear')


In [29]:
loaded_SVM_model.predict(tfidf) #hasil prediksi

array([-1])